
// TODO: HACKHACKHACKHACK
#define GLfloat float
#define GLuint int
#define GL_TEXTURE_1D 1
#define GL_TEXTURE_MAG_FILTER 0
#define GL_TEXTURE_MIN_FILTER 0
#define GL_TEXTURE_LINEAR 0
#define GL_MODELVIEW 0
#define GL_LINE_SMOOTH 0
#define GL_SRC_ALPHA 0
#define GL_PROJECTION 0
#define GL_ONE 0
#define GL_BLEND 0
#define GL_LIGHTING 0
#define GL_CULL_FACE 0
#define GL_DEPTH_TEST 0
#define GL_COLOR_MATERIAL 0
#define GL_LINEAR 0
#define GL_LINEAR_MIPMAP_NEAREST 0
#define GL_RGB 0
#define GL_UNSIGNED_BYTE 0
#define SDL_OPENGL 0
#define SDL_RESIZABLE 0
#define SDL_FULLSCREEN 0
#define GL_COLOR_BUFFER_BIT 0
#define GL_TRIANGLE_FAN 0
#define GL_LINE_LOOP 0
#define GL_LINES 0
#define GL_QUADS 0
#define GL_LINE_STRIP 0
